baseURL = "http://gardlt.io/"
languageCode = "en-us"
title = "Blog | gardlt.io"
theme = "ananke"

[params]
  github = "http://github.com/gardlt"
  twitter = "https://twitter.com/gardlt"
  linkedin = "http://www.linkedin.com/in/german-rivera-de-la-torre-4b265653"
  description = "The last theme you'll ever need. Maybe."